### ISSUE TITLE
Travis CI Build Time Improvement Request

### ISSUE THREAD

**Issue by jbadan** [SAP/ui5-server#173] opened 2019-03-28 19:38 UTC
The TravisCI environment is limited to 5 concurrent builds per org. The dependabot builds use all 5 builds at once: https://travis-ci.org/SAP/ui5-server/builds/512360621

Would you be willing to look into changing this configuration so they run serially, so that TravisCI resources can be distributed a bit more?

Thanks!

**Comment by RandomByte** [comment] 2019-03-28 21:22
Hey @jbadan,

This seems to be a duplicate of https://github.com/SAP/ui5-server/issues/115 opened by another member of your team. The answer we provided there is still valid.

Please note that Travis CI is currently performing bad for everyone, not just our organization. This is due to a serious interruption in their infrastructure: https://www.traviscistatus.com/incidents/my5wm56npf7q

However, we are currently working on transferring our infrastructure to Azure Pipelines. As this topic seems important for your team you might want to invest in that move as well: https://azure.microsoft.com/en-us/services/devops/pipelines/

Feel free to reach out to me via email if you are interested in that topic as well.

Closing as duplicate.

**Closed by RandomByte** 2019-03-28 21:22 UTC
Labels: duplicate

**Comment by jbadan** [comment] 2019-03-28 21:27
@RandomByte This is similar, but not actually a duplicate. I am specifically asking about your dependabot tasks. As they run automatically, it shouldn't affect your workflow to have them run serially instead of concurrently.

**Comment by RandomByte** [comment] 2019-03-28 23:07
Quote from https://github.com/SAP/ui5-server/issues/115:

> Most of our travis builds are currently related to releases of our modules and dependency updates done by @dependabot. Both is typically happening in multiple repositories simultaneously. **Limiting concurrent jobs per repository wont't have much effect on the overall load of our Travis org in these cases.**

Not sure how this is not related to this new issue.

@bcullman asked for the very same configuration change. Which AFAIK can not be limited to only affect dependabot PRs.
